spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie
    username: root
    password: admin
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true